version: '3'
services:
  yopinoji.info:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: npm run dev
    volumes:
      - /usr/src/node_modules
      - .:/usr/src
    environment:
      - NODE_ENV=development
